plugins {
    id "java"
    id 'java-library'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'io.papermc.paperweight.userdev' version '1.5.4'
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        url = uri("https://repo.aikar.co/content/groups/aikar/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        url = "https://oss.sonatype.org/content/groups/public/"
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri('https://repo.dmulloy2.net/repository/public/')
    }

    maven {
        url = uri('https://repo.codemc.io/repository/maven-snapshots/')
    }

    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {

    // Reobf
    paperweight.paperDevBundle "1.19.4-R0.1-SNAPSHOT"

    //Custom
    compileOnly 'fr.redbuild:models_spigot:1.0'

    api 'org.mongodb:mongodb-driver-sync:4.1.1'
    api 'org.mongodb:bson:4.3.4'

    // API
    compileOnly 'net.kyori:adventure-api:4.12.0'
    compileOnly 'net.kyori:adventure-text-minimessage:4.12.0'
    compileOnly 'net.kyori:adventure-text-serializer-gson:4.12.0'
    compileOnly 'net.kyori:adventure-text-serializer-plain:4.12.0'
    compileOnly 'net.kyori:adventure-text-serializer-legacy:4.12.0'
    // Minecraft

    compileOnly 'io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT'
    compileOnly 'io.papermc.paper:paper-server:1.19.4-R0.1-SNAPSHOT:mojang-mapped'
    compileOnly 'com.mojang:datafixerupper:6.0.6'
    compileOnly 'com.mojang:authlib:3.17.30'
    compileOnly 'com.mojang:brigadier:1.0.18'

    //Lombok
    compileOnly 'org.projectlombok:lombok:1.18.26'
	annotationProcessor 'org.projectlombok:lombok:1.18.26'
	
	testCompileOnly 'org.projectlombok:lombok:1.18.26'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'
    //Reflections
    implementation 'org.reflections:reflections:0.10.2'

}

archivesBaseName = "jar-filename"

def javaVersion = JavaVersion.VERSION_17

java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    toolchain.languageVersion = JavaLanguageVersion.of(javaVersion.toString())
}

tasks.withType(JavaCompile).configureEach {
    //options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"
    options.release = javaVersion.toString() as Integer
}

group = 'fr.redbuild'
version = '1.0'
description = 'models_paper'
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17
compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

publishing {
    publications {
        mavenJava(MavenPublication) {
            from(components.java)
        }
    }
}